In [1]:
s = "Hi I am Malini!"

In [2]:
s=s.split()

In [3]:
s

['Hi', 'I', 'am', 'Malini!']

In [4]:
planet = "Mars"
diameter = 12345

In [5]:
(f"The diameter of '{planet}' is '{diameter}' kilometers")

"The diameter of 'Mars' is '12345' kilometers"

In [6]:
d = {'k1':[1,2,3,{'trichy':['oh','man','inception',{'target':[1,2,3,'Haii']}]}]}

In [7]:
d['k1'][3]['trichy'][3]['target'][3]

'Haii'

In [8]:
import numpy as np

In [10]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [12]:
np.ones(10)*2

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [13]:
np.arange(20,40,4)

array([20, 24, 28, 32, 36])

In [17]:
value=[1,2,3,4,5,6,7,8,9]

In [18]:
value=np.array(value)

In [19]:
value.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [21]:
a = np.array([1, 2, 3, 4, 5])

In [22]:
b = np.array([6, 7, 8, 9, 10])

In [23]:
np.concatenate ((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
import pandas as pd

In [25]:
d={'a':1 , 'b':2 , 'c':3}

In [26]:
label=['num1','num2','num3','num4']

In [27]:
c=pd.DataFrame(d,index=label)

In [28]:
c.iloc[:3]

a  b  c
num1  1  2  3
num2  1  2  3
num3  1  2  3

In [29]:
import pandas as pd

In [30]:
import numpy as np

In [31]:
lists = [[1, 'aaa', 11], [2, 'bbb', 22], [3, 'ccc', 33]]

In [32]:
arr=np.array(lists)

In [33]:
df=pd.DataFrame(arr)

In [34]:
df

0    1   2
0  1  aaa  11
1  2  bbb  22
2  3  ccc  33